

GET http://localhost:3000/healthcheck

###
GET http://localhost:3000/airports

###
POST http://localhost:3000/airports
Content-Type: application/json

{
  "airliner_name": "American Airlines1",
  "airport_location": "Buffalo1",
  "airport_code": "BUF1",
  "airport_name": "Buffalo Niagara International Airport1"
}

###
DELETE  http://localhost:3000/airports/BUF1

###
GET http://localhost:3000/flights

###
POST http://localhost:3000/flights
Content-Type: application/json

{
  "flight_number": "006A31",
  "departure_location": "abc1",
  "destination_location": "tdd1"
}

###
DELETE  http://localhost:3000/flights/006A31